#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan  4 09:37:27 2023

@author: francesco

Stage 2: for each dataset generated in stage 1, run a Keras Hyperband search
over a 2-hidden-layer FFNN, retrain the best model, and save the tuned model
together with the (now-normalized) dataset.
"""
import os
import shutil

import tensorflow as tf
import keras_tuner as kt
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from common import config
from common.normalization import training_based_normalization

# detect available datasets generated by stage 1
folders = os.listdir(config.GENERATED_DATASETS_DIR)
try:
    folders.remove('.DS_Store')
except ValueError:
    pass

config.TUNER_TRIALS_DIR.mkdir(parents=True, exist_ok=True)
config.TUNED_DATASETS_DIR.mkdir(parents=True, exist_ok=True)

# iterate on all the folders containing the training and testing sets
for folder in folders:

    dataset_dir = config.GENERATED_DATASETS_DIR / folder

    # load the training set and the target
    train_x = pd.read_csv(dataset_dir / f'x_train_{folder}.csv', index_col=0)
    train_y = pd.read_csv(dataset_dir / f'y_train_{folder}.csv', index_col=0)
    # drop "month" columns from x dataset
    train_x = train_x.drop(columns=['beginning_month', 'beginning_day', 'beginning_year'])
    # concatenate input and targets to allow coherent shuffling
    data = pd.concat([train_x, train_y], axis=1)
    # shuffle training set
    shuffled = data.sample(frac=1)
    # divide data in train_x and train_y
    train_x = shuffled[list(train_x.columns)].to_numpy()
    train_y = shuffled[list(train_y.columns)].to_numpy()
    # define validation percentage
    val_perc = 0.2
    # determine limit training-validation
    limit = round(len(train_x) * (1 - val_perc))
    # divide training and validation
    x_train = train_x[:limit, :]
    y_train = train_y[:limit, :]
    x_val = train_x[limit:, :]
    y_val = train_y[limit:, :]
    # normalize training and validation based on mean and std only of the training
    x_train, x_val, means, stds = training_based_normalization(x_train, x_val)
    # save means and stds to reproduce normalization
    np.save(dataset_dir / f'means_{folder}', means)
    np.save(dataset_dir / f'stds_{folder}', stds)
    # identify number of features of the current dataset
    cols = train_x.shape[1]

    def model_builder_2layer(hp):

        model = tf.keras.models.Sequential()
        model.add(tf.keras.layers.Input(shape=(cols,)))

        hp_activation = hp.Choice('activation', values=['relu', 'sigmoid'])
        hp_layer_1 = hp.Int('layer_1', min_value=5, max_value=30, step=1)
        hp_layer_2 = hp.Int('layer_2', min_value=5, max_value=30, step=1)
        hp_learning_rate = hp.Choice('learning_rate', values=[0.001, 0.01, 0.1])

        model.add(tf.keras.layers.Dense(units=hp_layer_1, activation=hp_activation))
        model.add(tf.keras.layers.Dense(units=hp_layer_2, activation=hp_activation))
        model.add(tf.keras.layers.Dense(1))

        optimizer = tf.keras.optimizers.Adam(hp_learning_rate)
        loss = tf.keras.losses.MeanSquaredError()
        model.compile(optimizer=optimizer, loss=loss)

        return model

    tuner2 = kt.Hyperband(model_builder_2layer,
                          objective='val_loss',
                          max_epochs=200,
                          factor=3,
                          directory=str(config.TUNER_TRIALS_DIR),
                          project_name=folder)

    stop_early = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10)
    tuner2.search(x_train, y_train, epochs=200, validation_data=(x_val, y_val), callbacks=[stop_early])

    best_hps = tuner2.get_best_hyperparameters(1)[0]
    model = tuner2.hypermodel.build(best_hps)
    report = model.fit(x_train, y_train, epochs=200, validation_data=(x_val, y_val), callbacks=[stop_early])
    loss = pd.DataFrame(report.history)
    loss.plot()
    plt.show()

    model_dir = config.TUNER_TRIALS_DIR / folder
    model_dir.mkdir(parents=True, exist_ok=True)
    loss.to_csv(model_dir / 'loss.csv')
    model.save(model_dir / 'model')

    tuned_dir = config.TUNED_DATASETS_DIR / folder
    try:
        # delete folder in the new location if it already exists
        shutil.rmtree(tuned_dir)
    except FileNotFoundError:
        pass
    # move the folder from generated_datasets to tuned_datasets
    os.rename(dataset_dir, tuned_dir)
